/*
Channel Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channelmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChannelmanagerGetChannelWithAssociationsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelmanagerGetChannelWithAssociationsRequest{}

// ChannelmanagerGetChannelWithAssociationsRequest struct for ChannelmanagerGetChannelWithAssociationsRequest
type ChannelmanagerGetChannelWithAssociationsRequest struct {
	TenantId string `json:"tenantId"`
	Id string `json:"id"`
}

type _ChannelmanagerGetChannelWithAssociationsRequest ChannelmanagerGetChannelWithAssociationsRequest

// NewChannelmanagerGetChannelWithAssociationsRequest instantiates a new ChannelmanagerGetChannelWithAssociationsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelmanagerGetChannelWithAssociationsRequest(tenantId string, id string) *ChannelmanagerGetChannelWithAssociationsRequest {
	this := ChannelmanagerGetChannelWithAssociationsRequest{}
	this.TenantId = tenantId
	this.Id = id
	return &this
}

// NewChannelmanagerGetChannelWithAssociationsRequestWithDefaults instantiates a new ChannelmanagerGetChannelWithAssociationsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelmanagerGetChannelWithAssociationsRequestWithDefaults() *ChannelmanagerGetChannelWithAssociationsRequest {
	this := ChannelmanagerGetChannelWithAssociationsRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *ChannelmanagerGetChannelWithAssociationsRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *ChannelmanagerGetChannelWithAssociationsRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *ChannelmanagerGetChannelWithAssociationsRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetId returns the Id field value
func (o *ChannelmanagerGetChannelWithAssociationsRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChannelmanagerGetChannelWithAssociationsRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChannelmanagerGetChannelWithAssociationsRequest) SetId(v string) {
	o.Id = v
}

func (o ChannelmanagerGetChannelWithAssociationsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelmanagerGetChannelWithAssociationsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ChannelmanagerGetChannelWithAssociationsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChannelmanagerGetChannelWithAssociationsRequest := _ChannelmanagerGetChannelWithAssociationsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChannelmanagerGetChannelWithAssociationsRequest)

	if err != nil {
		return err
	}

	*o = ChannelmanagerGetChannelWithAssociationsRequest(varChannelmanagerGetChannelWithAssociationsRequest)

	return err
}

type NullableChannelmanagerGetChannelWithAssociationsRequest struct {
	value *ChannelmanagerGetChannelWithAssociationsRequest
	isSet bool
}

func (v NullableChannelmanagerGetChannelWithAssociationsRequest) Get() *ChannelmanagerGetChannelWithAssociationsRequest {
	return v.value
}

func (v *NullableChannelmanagerGetChannelWithAssociationsRequest) Set(val *ChannelmanagerGetChannelWithAssociationsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelmanagerGetChannelWithAssociationsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelmanagerGetChannelWithAssociationsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelmanagerGetChannelWithAssociationsRequest(val *ChannelmanagerGetChannelWithAssociationsRequest) *NullableChannelmanagerGetChannelWithAssociationsRequest {
	return &NullableChannelmanagerGetChannelWithAssociationsRequest{value: val, isSet: true}
}

func (v NullableChannelmanagerGetChannelWithAssociationsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelmanagerGetChannelWithAssociationsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


