/*
Channel Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channelmanager

import (
	"encoding/json"
)

// checks if the ChannelmanagerListChannelsWithAssociationsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelmanagerListChannelsWithAssociationsResponse{}

// ChannelmanagerListChannelsWithAssociationsResponse struct for ChannelmanagerListChannelsWithAssociationsResponse
type ChannelmanagerListChannelsWithAssociationsResponse struct {
	Channels []ChannelmanagerChannelResponseWithAssociations `json:"channels,omitempty"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// NewChannelmanagerListChannelsWithAssociationsResponse instantiates a new ChannelmanagerListChannelsWithAssociationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelmanagerListChannelsWithAssociationsResponse() *ChannelmanagerListChannelsWithAssociationsResponse {
	this := ChannelmanagerListChannelsWithAssociationsResponse{}
	return &this
}

// NewChannelmanagerListChannelsWithAssociationsResponseWithDefaults instantiates a new ChannelmanagerListChannelsWithAssociationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelmanagerListChannelsWithAssociationsResponseWithDefaults() *ChannelmanagerListChannelsWithAssociationsResponse {
	this := ChannelmanagerListChannelsWithAssociationsResponse{}
	return &this
}

// GetChannels returns the Channels field value if set, zero value otherwise.
func (o *ChannelmanagerListChannelsWithAssociationsResponse) GetChannels() []ChannelmanagerChannelResponseWithAssociations {
	if o == nil || IsNil(o.Channels) {
		var ret []ChannelmanagerChannelResponseWithAssociations
		return ret
	}
	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerListChannelsWithAssociationsResponse) GetChannelsOk() ([]ChannelmanagerChannelResponseWithAssociations, bool) {
	if o == nil || IsNil(o.Channels) {
		return nil, false
	}
	return o.Channels, true
}

// HasChannels returns a boolean if a field has been set.
func (o *ChannelmanagerListChannelsWithAssociationsResponse) HasChannels() bool {
	if o != nil && !IsNil(o.Channels) {
		return true
	}

	return false
}

// SetChannels gets a reference to the given []ChannelmanagerChannelResponseWithAssociations and assigns it to the Channels field.
func (o *ChannelmanagerListChannelsWithAssociationsResponse) SetChannels(v []ChannelmanagerChannelResponseWithAssociations) {
	o.Channels = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *ChannelmanagerListChannelsWithAssociationsResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerListChannelsWithAssociationsResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ChannelmanagerListChannelsWithAssociationsResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *ChannelmanagerListChannelsWithAssociationsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o ChannelmanagerListChannelsWithAssociationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelmanagerListChannelsWithAssociationsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Channels) {
		toSerialize["channels"] = o.Channels
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	return toSerialize, nil
}

type NullableChannelmanagerListChannelsWithAssociationsResponse struct {
	value *ChannelmanagerListChannelsWithAssociationsResponse
	isSet bool
}

func (v NullableChannelmanagerListChannelsWithAssociationsResponse) Get() *ChannelmanagerListChannelsWithAssociationsResponse {
	return v.value
}

func (v *NullableChannelmanagerListChannelsWithAssociationsResponse) Set(val *ChannelmanagerListChannelsWithAssociationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelmanagerListChannelsWithAssociationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelmanagerListChannelsWithAssociationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelmanagerListChannelsWithAssociationsResponse(val *ChannelmanagerListChannelsWithAssociationsResponse) *NullableChannelmanagerListChannelsWithAssociationsResponse {
	return &NullableChannelmanagerListChannelsWithAssociationsResponse{value: val, isSet: true}
}

func (v NullableChannelmanagerListChannelsWithAssociationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelmanagerListChannelsWithAssociationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


