/*
Channel Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channelmanager

import (
	"encoding/json"
)

// checks if the ChannelmanagerMarketResponseWithAssociationsAssociation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelmanagerMarketResponseWithAssociationsAssociation{}

// ChannelmanagerMarketResponseWithAssociationsAssociation struct for ChannelmanagerMarketResponseWithAssociationsAssociation
type ChannelmanagerMarketResponseWithAssociationsAssociation struct {
	Channel *ChannelmanagerChannelResponse `json:"channel,omitempty"`
}

// NewChannelmanagerMarketResponseWithAssociationsAssociation instantiates a new ChannelmanagerMarketResponseWithAssociationsAssociation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelmanagerMarketResponseWithAssociationsAssociation() *ChannelmanagerMarketResponseWithAssociationsAssociation {
	this := ChannelmanagerMarketResponseWithAssociationsAssociation{}
	return &this
}

// NewChannelmanagerMarketResponseWithAssociationsAssociationWithDefaults instantiates a new ChannelmanagerMarketResponseWithAssociationsAssociation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelmanagerMarketResponseWithAssociationsAssociationWithDefaults() *ChannelmanagerMarketResponseWithAssociationsAssociation {
	this := ChannelmanagerMarketResponseWithAssociationsAssociation{}
	return &this
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *ChannelmanagerMarketResponseWithAssociationsAssociation) GetChannel() ChannelmanagerChannelResponse {
	if o == nil || IsNil(o.Channel) {
		var ret ChannelmanagerChannelResponse
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerMarketResponseWithAssociationsAssociation) GetChannelOk() (*ChannelmanagerChannelResponse, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *ChannelmanagerMarketResponseWithAssociationsAssociation) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given ChannelmanagerChannelResponse and assigns it to the Channel field.
func (o *ChannelmanagerMarketResponseWithAssociationsAssociation) SetChannel(v ChannelmanagerChannelResponse) {
	o.Channel = &v
}

func (o ChannelmanagerMarketResponseWithAssociationsAssociation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelmanagerMarketResponseWithAssociationsAssociation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	return toSerialize, nil
}

type NullableChannelmanagerMarketResponseWithAssociationsAssociation struct {
	value *ChannelmanagerMarketResponseWithAssociationsAssociation
	isSet bool
}

func (v NullableChannelmanagerMarketResponseWithAssociationsAssociation) Get() *ChannelmanagerMarketResponseWithAssociationsAssociation {
	return v.value
}

func (v *NullableChannelmanagerMarketResponseWithAssociationsAssociation) Set(val *ChannelmanagerMarketResponseWithAssociationsAssociation) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelmanagerMarketResponseWithAssociationsAssociation) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelmanagerMarketResponseWithAssociationsAssociation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelmanagerMarketResponseWithAssociationsAssociation(val *ChannelmanagerMarketResponseWithAssociationsAssociation) *NullableChannelmanagerMarketResponseWithAssociationsAssociation {
	return &NullableChannelmanagerMarketResponseWithAssociationsAssociation{value: val, isSet: true}
}

func (v NullableChannelmanagerMarketResponseWithAssociationsAssociation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelmanagerMarketResponseWithAssociationsAssociation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


