/*
Channel Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channelmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChannelmanagerDeleteAssociationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelmanagerDeleteAssociationRequest{}

// ChannelmanagerDeleteAssociationRequest struct for ChannelmanagerDeleteAssociationRequest
type ChannelmanagerDeleteAssociationRequest struct {
	TenantId string `json:"tenantId"`
	Id string `json:"id"`
}

type _ChannelmanagerDeleteAssociationRequest ChannelmanagerDeleteAssociationRequest

// NewChannelmanagerDeleteAssociationRequest instantiates a new ChannelmanagerDeleteAssociationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelmanagerDeleteAssociationRequest(tenantId string, id string) *ChannelmanagerDeleteAssociationRequest {
	this := ChannelmanagerDeleteAssociationRequest{}
	this.TenantId = tenantId
	this.Id = id
	return &this
}

// NewChannelmanagerDeleteAssociationRequestWithDefaults instantiates a new ChannelmanagerDeleteAssociationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelmanagerDeleteAssociationRequestWithDefaults() *ChannelmanagerDeleteAssociationRequest {
	this := ChannelmanagerDeleteAssociationRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *ChannelmanagerDeleteAssociationRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *ChannelmanagerDeleteAssociationRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *ChannelmanagerDeleteAssociationRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetId returns the Id field value
func (o *ChannelmanagerDeleteAssociationRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChannelmanagerDeleteAssociationRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChannelmanagerDeleteAssociationRequest) SetId(v string) {
	o.Id = v
}

func (o ChannelmanagerDeleteAssociationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelmanagerDeleteAssociationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ChannelmanagerDeleteAssociationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChannelmanagerDeleteAssociationRequest := _ChannelmanagerDeleteAssociationRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChannelmanagerDeleteAssociationRequest)

	if err != nil {
		return err
	}

	*o = ChannelmanagerDeleteAssociationRequest(varChannelmanagerDeleteAssociationRequest)

	return err
}

type NullableChannelmanagerDeleteAssociationRequest struct {
	value *ChannelmanagerDeleteAssociationRequest
	isSet bool
}

func (v NullableChannelmanagerDeleteAssociationRequest) Get() *ChannelmanagerDeleteAssociationRequest {
	return v.value
}

func (v *NullableChannelmanagerDeleteAssociationRequest) Set(val *ChannelmanagerDeleteAssociationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelmanagerDeleteAssociationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelmanagerDeleteAssociationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelmanagerDeleteAssociationRequest(val *ChannelmanagerDeleteAssociationRequest) *NullableChannelmanagerDeleteAssociationRequest {
	return &NullableChannelmanagerDeleteAssociationRequest{value: val, isSet: true}
}

func (v NullableChannelmanagerDeleteAssociationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelmanagerDeleteAssociationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


