/*
Channel Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channelmanager

import (
	"encoding/json"
)

// checks if the ChannelmanagerChannelResponseWithAssociationsAssociation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelmanagerChannelResponseWithAssociationsAssociation{}

// ChannelmanagerChannelResponseWithAssociationsAssociation struct for ChannelmanagerChannelResponseWithAssociationsAssociation
type ChannelmanagerChannelResponseWithAssociationsAssociation struct {
	Market *ChannelmanagerMarketResponse `json:"market,omitempty"`
}

// NewChannelmanagerChannelResponseWithAssociationsAssociation instantiates a new ChannelmanagerChannelResponseWithAssociationsAssociation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelmanagerChannelResponseWithAssociationsAssociation() *ChannelmanagerChannelResponseWithAssociationsAssociation {
	this := ChannelmanagerChannelResponseWithAssociationsAssociation{}
	return &this
}

// NewChannelmanagerChannelResponseWithAssociationsAssociationWithDefaults instantiates a new ChannelmanagerChannelResponseWithAssociationsAssociation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelmanagerChannelResponseWithAssociationsAssociationWithDefaults() *ChannelmanagerChannelResponseWithAssociationsAssociation {
	this := ChannelmanagerChannelResponseWithAssociationsAssociation{}
	return &this
}

// GetMarket returns the Market field value if set, zero value otherwise.
func (o *ChannelmanagerChannelResponseWithAssociationsAssociation) GetMarket() ChannelmanagerMarketResponse {
	if o == nil || IsNil(o.Market) {
		var ret ChannelmanagerMarketResponse
		return ret
	}
	return *o.Market
}

// GetMarketOk returns a tuple with the Market field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerChannelResponseWithAssociationsAssociation) GetMarketOk() (*ChannelmanagerMarketResponse, bool) {
	if o == nil || IsNil(o.Market) {
		return nil, false
	}
	return o.Market, true
}

// HasMarket returns a boolean if a field has been set.
func (o *ChannelmanagerChannelResponseWithAssociationsAssociation) HasMarket() bool {
	if o != nil && !IsNil(o.Market) {
		return true
	}

	return false
}

// SetMarket gets a reference to the given ChannelmanagerMarketResponse and assigns it to the Market field.
func (o *ChannelmanagerChannelResponseWithAssociationsAssociation) SetMarket(v ChannelmanagerMarketResponse) {
	o.Market = &v
}

func (o ChannelmanagerChannelResponseWithAssociationsAssociation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelmanagerChannelResponseWithAssociationsAssociation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Market) {
		toSerialize["market"] = o.Market
	}
	return toSerialize, nil
}

type NullableChannelmanagerChannelResponseWithAssociationsAssociation struct {
	value *ChannelmanagerChannelResponseWithAssociationsAssociation
	isSet bool
}

func (v NullableChannelmanagerChannelResponseWithAssociationsAssociation) Get() *ChannelmanagerChannelResponseWithAssociationsAssociation {
	return v.value
}

func (v *NullableChannelmanagerChannelResponseWithAssociationsAssociation) Set(val *ChannelmanagerChannelResponseWithAssociationsAssociation) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelmanagerChannelResponseWithAssociationsAssociation) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelmanagerChannelResponseWithAssociationsAssociation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelmanagerChannelResponseWithAssociationsAssociation(val *ChannelmanagerChannelResponseWithAssociationsAssociation) *NullableChannelmanagerChannelResponseWithAssociationsAssociation {
	return &NullableChannelmanagerChannelResponseWithAssociationsAssociation{value: val, isSet: true}
}

func (v NullableChannelmanagerChannelResponseWithAssociationsAssociation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelmanagerChannelResponseWithAssociationsAssociation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


