/*
Channel Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channelmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChannelmanagerDeleteMarketRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelmanagerDeleteMarketRequest{}

// ChannelmanagerDeleteMarketRequest struct for ChannelmanagerDeleteMarketRequest
type ChannelmanagerDeleteMarketRequest struct {
	TenantId string `json:"tenantId"`
	Id string `json:"id"`
}

type _ChannelmanagerDeleteMarketRequest ChannelmanagerDeleteMarketRequest

// NewChannelmanagerDeleteMarketRequest instantiates a new ChannelmanagerDeleteMarketRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelmanagerDeleteMarketRequest(tenantId string, id string) *ChannelmanagerDeleteMarketRequest {
	this := ChannelmanagerDeleteMarketRequest{}
	this.TenantId = tenantId
	this.Id = id
	return &this
}

// NewChannelmanagerDeleteMarketRequestWithDefaults instantiates a new ChannelmanagerDeleteMarketRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelmanagerDeleteMarketRequestWithDefaults() *ChannelmanagerDeleteMarketRequest {
	this := ChannelmanagerDeleteMarketRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *ChannelmanagerDeleteMarketRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *ChannelmanagerDeleteMarketRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *ChannelmanagerDeleteMarketRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetId returns the Id field value
func (o *ChannelmanagerDeleteMarketRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChannelmanagerDeleteMarketRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChannelmanagerDeleteMarketRequest) SetId(v string) {
	o.Id = v
}

func (o ChannelmanagerDeleteMarketRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelmanagerDeleteMarketRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ChannelmanagerDeleteMarketRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChannelmanagerDeleteMarketRequest := _ChannelmanagerDeleteMarketRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChannelmanagerDeleteMarketRequest)

	if err != nil {
		return err
	}

	*o = ChannelmanagerDeleteMarketRequest(varChannelmanagerDeleteMarketRequest)

	return err
}

type NullableChannelmanagerDeleteMarketRequest struct {
	value *ChannelmanagerDeleteMarketRequest
	isSet bool
}

func (v NullableChannelmanagerDeleteMarketRequest) Get() *ChannelmanagerDeleteMarketRequest {
	return v.value
}

func (v *NullableChannelmanagerDeleteMarketRequest) Set(val *ChannelmanagerDeleteMarketRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelmanagerDeleteMarketRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelmanagerDeleteMarketRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelmanagerDeleteMarketRequest(val *ChannelmanagerDeleteMarketRequest) *NullableChannelmanagerDeleteMarketRequest {
	return &NullableChannelmanagerDeleteMarketRequest{value: val, isSet: true}
}

func (v NullableChannelmanagerDeleteMarketRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelmanagerDeleteMarketRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


