/*
Channel Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channelmanager

import (
	"encoding/json"
)

// checks if the ChannelmanagerAssociationResponseAssociation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelmanagerAssociationResponseAssociation{}

// ChannelmanagerAssociationResponseAssociation struct for ChannelmanagerAssociationResponseAssociation
type ChannelmanagerAssociationResponseAssociation struct {
	ChannelGrn *string `json:"channelGrn,omitempty"`
	MarketGrn *string `json:"marketGrn,omitempty"`
}

// NewChannelmanagerAssociationResponseAssociation instantiates a new ChannelmanagerAssociationResponseAssociation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelmanagerAssociationResponseAssociation() *ChannelmanagerAssociationResponseAssociation {
	this := ChannelmanagerAssociationResponseAssociation{}
	return &this
}

// NewChannelmanagerAssociationResponseAssociationWithDefaults instantiates a new ChannelmanagerAssociationResponseAssociation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelmanagerAssociationResponseAssociationWithDefaults() *ChannelmanagerAssociationResponseAssociation {
	this := ChannelmanagerAssociationResponseAssociation{}
	return &this
}

// GetChannelGrn returns the ChannelGrn field value if set, zero value otherwise.
func (o *ChannelmanagerAssociationResponseAssociation) GetChannelGrn() string {
	if o == nil || IsNil(o.ChannelGrn) {
		var ret string
		return ret
	}
	return *o.ChannelGrn
}

// GetChannelGrnOk returns a tuple with the ChannelGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerAssociationResponseAssociation) GetChannelGrnOk() (*string, bool) {
	if o == nil || IsNil(o.ChannelGrn) {
		return nil, false
	}
	return o.ChannelGrn, true
}

// HasChannelGrn returns a boolean if a field has been set.
func (o *ChannelmanagerAssociationResponseAssociation) HasChannelGrn() bool {
	if o != nil && !IsNil(o.ChannelGrn) {
		return true
	}

	return false
}

// SetChannelGrn gets a reference to the given string and assigns it to the ChannelGrn field.
func (o *ChannelmanagerAssociationResponseAssociation) SetChannelGrn(v string) {
	o.ChannelGrn = &v
}

// GetMarketGrn returns the MarketGrn field value if set, zero value otherwise.
func (o *ChannelmanagerAssociationResponseAssociation) GetMarketGrn() string {
	if o == nil || IsNil(o.MarketGrn) {
		var ret string
		return ret
	}
	return *o.MarketGrn
}

// GetMarketGrnOk returns a tuple with the MarketGrn field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerAssociationResponseAssociation) GetMarketGrnOk() (*string, bool) {
	if o == nil || IsNil(o.MarketGrn) {
		return nil, false
	}
	return o.MarketGrn, true
}

// HasMarketGrn returns a boolean if a field has been set.
func (o *ChannelmanagerAssociationResponseAssociation) HasMarketGrn() bool {
	if o != nil && !IsNil(o.MarketGrn) {
		return true
	}

	return false
}

// SetMarketGrn gets a reference to the given string and assigns it to the MarketGrn field.
func (o *ChannelmanagerAssociationResponseAssociation) SetMarketGrn(v string) {
	o.MarketGrn = &v
}

func (o ChannelmanagerAssociationResponseAssociation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelmanagerAssociationResponseAssociation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChannelGrn) {
		toSerialize["channelGrn"] = o.ChannelGrn
	}
	if !IsNil(o.MarketGrn) {
		toSerialize["marketGrn"] = o.MarketGrn
	}
	return toSerialize, nil
}

type NullableChannelmanagerAssociationResponseAssociation struct {
	value *ChannelmanagerAssociationResponseAssociation
	isSet bool
}

func (v NullableChannelmanagerAssociationResponseAssociation) Get() *ChannelmanagerAssociationResponseAssociation {
	return v.value
}

func (v *NullableChannelmanagerAssociationResponseAssociation) Set(val *ChannelmanagerAssociationResponseAssociation) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelmanagerAssociationResponseAssociation) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelmanagerAssociationResponseAssociation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelmanagerAssociationResponseAssociation(val *ChannelmanagerAssociationResponseAssociation) *NullableChannelmanagerAssociationResponseAssociation {
	return &NullableChannelmanagerAssociationResponseAssociation{value: val, isSet: true}
}

func (v NullableChannelmanagerAssociationResponseAssociation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelmanagerAssociationResponseAssociation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


