/*
Channel Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channelmanager

import (
	"encoding/json"
)

// checks if the ChannelmanagerListMarketsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelmanagerListMarketsResponse{}

// ChannelmanagerListMarketsResponse struct for ChannelmanagerListMarketsResponse
type ChannelmanagerListMarketsResponse struct {
	Markets []ChannelmanagerMarketResponse `json:"markets,omitempty"`
	NextPageToken *string `json:"nextPageToken,omitempty"`
}

// NewChannelmanagerListMarketsResponse instantiates a new ChannelmanagerListMarketsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelmanagerListMarketsResponse() *ChannelmanagerListMarketsResponse {
	this := ChannelmanagerListMarketsResponse{}
	return &this
}

// NewChannelmanagerListMarketsResponseWithDefaults instantiates a new ChannelmanagerListMarketsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelmanagerListMarketsResponseWithDefaults() *ChannelmanagerListMarketsResponse {
	this := ChannelmanagerListMarketsResponse{}
	return &this
}

// GetMarkets returns the Markets field value if set, zero value otherwise.
func (o *ChannelmanagerListMarketsResponse) GetMarkets() []ChannelmanagerMarketResponse {
	if o == nil || IsNil(o.Markets) {
		var ret []ChannelmanagerMarketResponse
		return ret
	}
	return o.Markets
}

// GetMarketsOk returns a tuple with the Markets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerListMarketsResponse) GetMarketsOk() ([]ChannelmanagerMarketResponse, bool) {
	if o == nil || IsNil(o.Markets) {
		return nil, false
	}
	return o.Markets, true
}

// HasMarkets returns a boolean if a field has been set.
func (o *ChannelmanagerListMarketsResponse) HasMarkets() bool {
	if o != nil && !IsNil(o.Markets) {
		return true
	}

	return false
}

// SetMarkets gets a reference to the given []ChannelmanagerMarketResponse and assigns it to the Markets field.
func (o *ChannelmanagerListMarketsResponse) SetMarkets(v []ChannelmanagerMarketResponse) {
	o.Markets = v
}

// GetNextPageToken returns the NextPageToken field value if set, zero value otherwise.
func (o *ChannelmanagerListMarketsResponse) GetNextPageToken() string {
	if o == nil || IsNil(o.NextPageToken) {
		var ret string
		return ret
	}
	return *o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerListMarketsResponse) GetNextPageTokenOk() (*string, bool) {
	if o == nil || IsNil(o.NextPageToken) {
		return nil, false
	}
	return o.NextPageToken, true
}

// HasNextPageToken returns a boolean if a field has been set.
func (o *ChannelmanagerListMarketsResponse) HasNextPageToken() bool {
	if o != nil && !IsNil(o.NextPageToken) {
		return true
	}

	return false
}

// SetNextPageToken gets a reference to the given string and assigns it to the NextPageToken field.
func (o *ChannelmanagerListMarketsResponse) SetNextPageToken(v string) {
	o.NextPageToken = &v
}

func (o ChannelmanagerListMarketsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelmanagerListMarketsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Markets) {
		toSerialize["markets"] = o.Markets
	}
	if !IsNil(o.NextPageToken) {
		toSerialize["nextPageToken"] = o.NextPageToken
	}
	return toSerialize, nil
}

type NullableChannelmanagerListMarketsResponse struct {
	value *ChannelmanagerListMarketsResponse
	isSet bool
}

func (v NullableChannelmanagerListMarketsResponse) Get() *ChannelmanagerListMarketsResponse {
	return v.value
}

func (v *NullableChannelmanagerListMarketsResponse) Set(val *ChannelmanagerListMarketsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelmanagerListMarketsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelmanagerListMarketsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelmanagerListMarketsResponse(val *ChannelmanagerListMarketsResponse) *NullableChannelmanagerListMarketsResponse {
	return &NullableChannelmanagerListMarketsResponse{value: val, isSet: true}
}

func (v NullableChannelmanagerListMarketsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelmanagerListMarketsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


