/*
Channel Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channelmanager

import (
	"encoding/json"
)

// checks if the ChannelmanagerChannelTypeWebsite type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelmanagerChannelTypeWebsite{}

// ChannelmanagerChannelTypeWebsite struct for ChannelmanagerChannelTypeWebsite
type ChannelmanagerChannelTypeWebsite struct {
	Domain *string `json:"domain,omitempty"`
}

// NewChannelmanagerChannelTypeWebsite instantiates a new ChannelmanagerChannelTypeWebsite object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelmanagerChannelTypeWebsite() *ChannelmanagerChannelTypeWebsite {
	this := ChannelmanagerChannelTypeWebsite{}
	return &this
}

// NewChannelmanagerChannelTypeWebsiteWithDefaults instantiates a new ChannelmanagerChannelTypeWebsite object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelmanagerChannelTypeWebsiteWithDefaults() *ChannelmanagerChannelTypeWebsite {
	this := ChannelmanagerChannelTypeWebsite{}
	return &this
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *ChannelmanagerChannelTypeWebsite) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerChannelTypeWebsite) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *ChannelmanagerChannelTypeWebsite) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *ChannelmanagerChannelTypeWebsite) SetDomain(v string) {
	o.Domain = &v
}

func (o ChannelmanagerChannelTypeWebsite) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelmanagerChannelTypeWebsite) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	return toSerialize, nil
}

type NullableChannelmanagerChannelTypeWebsite struct {
	value *ChannelmanagerChannelTypeWebsite
	isSet bool
}

func (v NullableChannelmanagerChannelTypeWebsite) Get() *ChannelmanagerChannelTypeWebsite {
	return v.value
}

func (v *NullableChannelmanagerChannelTypeWebsite) Set(val *ChannelmanagerChannelTypeWebsite) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelmanagerChannelTypeWebsite) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelmanagerChannelTypeWebsite) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelmanagerChannelTypeWebsite(val *ChannelmanagerChannelTypeWebsite) *NullableChannelmanagerChannelTypeWebsite {
	return &NullableChannelmanagerChannelTypeWebsite{value: val, isSet: true}
}

func (v NullableChannelmanagerChannelTypeWebsite) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelmanagerChannelTypeWebsite) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


