/*
Channel Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channelmanager

import (
	"encoding/json"
)

// checks if the ChannelmanagerChannelSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelmanagerChannelSettings{}

// ChannelmanagerChannelSettings struct for ChannelmanagerChannelSettings
type ChannelmanagerChannelSettings struct {
	HideOosProducts *bool `json:"hideOosProducts,omitempty"`
	HidePricelessProducts *bool `json:"hidePricelessProducts,omitempty"`
}

// NewChannelmanagerChannelSettings instantiates a new ChannelmanagerChannelSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelmanagerChannelSettings() *ChannelmanagerChannelSettings {
	this := ChannelmanagerChannelSettings{}
	return &this
}

// NewChannelmanagerChannelSettingsWithDefaults instantiates a new ChannelmanagerChannelSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelmanagerChannelSettingsWithDefaults() *ChannelmanagerChannelSettings {
	this := ChannelmanagerChannelSettings{}
	return &this
}

// GetHideOosProducts returns the HideOosProducts field value if set, zero value otherwise.
func (o *ChannelmanagerChannelSettings) GetHideOosProducts() bool {
	if o == nil || IsNil(o.HideOosProducts) {
		var ret bool
		return ret
	}
	return *o.HideOosProducts
}

// GetHideOosProductsOk returns a tuple with the HideOosProducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerChannelSettings) GetHideOosProductsOk() (*bool, bool) {
	if o == nil || IsNil(o.HideOosProducts) {
		return nil, false
	}
	return o.HideOosProducts, true
}

// HasHideOosProducts returns a boolean if a field has been set.
func (o *ChannelmanagerChannelSettings) HasHideOosProducts() bool {
	if o != nil && !IsNil(o.HideOosProducts) {
		return true
	}

	return false
}

// SetHideOosProducts gets a reference to the given bool and assigns it to the HideOosProducts field.
func (o *ChannelmanagerChannelSettings) SetHideOosProducts(v bool) {
	o.HideOosProducts = &v
}

// GetHidePricelessProducts returns the HidePricelessProducts field value if set, zero value otherwise.
func (o *ChannelmanagerChannelSettings) GetHidePricelessProducts() bool {
	if o == nil || IsNil(o.HidePricelessProducts) {
		var ret bool
		return ret
	}
	return *o.HidePricelessProducts
}

// GetHidePricelessProductsOk returns a tuple with the HidePricelessProducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerChannelSettings) GetHidePricelessProductsOk() (*bool, bool) {
	if o == nil || IsNil(o.HidePricelessProducts) {
		return nil, false
	}
	return o.HidePricelessProducts, true
}

// HasHidePricelessProducts returns a boolean if a field has been set.
func (o *ChannelmanagerChannelSettings) HasHidePricelessProducts() bool {
	if o != nil && !IsNil(o.HidePricelessProducts) {
		return true
	}

	return false
}

// SetHidePricelessProducts gets a reference to the given bool and assigns it to the HidePricelessProducts field.
func (o *ChannelmanagerChannelSettings) SetHidePricelessProducts(v bool) {
	o.HidePricelessProducts = &v
}

func (o ChannelmanagerChannelSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelmanagerChannelSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.HideOosProducts) {
		toSerialize["hideOosProducts"] = o.HideOosProducts
	}
	if !IsNil(o.HidePricelessProducts) {
		toSerialize["hidePricelessProducts"] = o.HidePricelessProducts
	}
	return toSerialize, nil
}

type NullableChannelmanagerChannelSettings struct {
	value *ChannelmanagerChannelSettings
	isSet bool
}

func (v NullableChannelmanagerChannelSettings) Get() *ChannelmanagerChannelSettings {
	return v.value
}

func (v *NullableChannelmanagerChannelSettings) Set(val *ChannelmanagerChannelSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelmanagerChannelSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelmanagerChannelSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelmanagerChannelSettings(val *ChannelmanagerChannelSettings) *NullableChannelmanagerChannelSettings {
	return &NullableChannelmanagerChannelSettings{value: val, isSet: true}
}

func (v NullableChannelmanagerChannelSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelmanagerChannelSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


