/*
Channel Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channelmanager

import (
	"encoding/json"
)

// checks if the ChannelmanagerDeleteChannelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelmanagerDeleteChannelRequest{}

// ChannelmanagerDeleteChannelRequest struct for ChannelmanagerDeleteChannelRequest
type ChannelmanagerDeleteChannelRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	Id *string `json:"id,omitempty"`
}

// NewChannelmanagerDeleteChannelRequest instantiates a new ChannelmanagerDeleteChannelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelmanagerDeleteChannelRequest() *ChannelmanagerDeleteChannelRequest {
	this := ChannelmanagerDeleteChannelRequest{}
	return &this
}

// NewChannelmanagerDeleteChannelRequestWithDefaults instantiates a new ChannelmanagerDeleteChannelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelmanagerDeleteChannelRequestWithDefaults() *ChannelmanagerDeleteChannelRequest {
	this := ChannelmanagerDeleteChannelRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ChannelmanagerDeleteChannelRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerDeleteChannelRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *ChannelmanagerDeleteChannelRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *ChannelmanagerDeleteChannelRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ChannelmanagerDeleteChannelRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerDeleteChannelRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ChannelmanagerDeleteChannelRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ChannelmanagerDeleteChannelRequest) SetId(v string) {
	o.Id = &v
}

func (o ChannelmanagerDeleteChannelRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelmanagerDeleteChannelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableChannelmanagerDeleteChannelRequest struct {
	value *ChannelmanagerDeleteChannelRequest
	isSet bool
}

func (v NullableChannelmanagerDeleteChannelRequest) Get() *ChannelmanagerDeleteChannelRequest {
	return v.value
}

func (v *NullableChannelmanagerDeleteChannelRequest) Set(val *ChannelmanagerDeleteChannelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelmanagerDeleteChannelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelmanagerDeleteChannelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelmanagerDeleteChannelRequest(val *ChannelmanagerDeleteChannelRequest) *NullableChannelmanagerDeleteChannelRequest {
	return &NullableChannelmanagerDeleteChannelRequest{value: val, isSet: true}
}

func (v NullableChannelmanagerDeleteChannelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelmanagerDeleteChannelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


