/*
Channel Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channelmanager

import (
	"encoding/json"
)

// checks if the ChannelmanagerCreateMarketRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelmanagerCreateMarketRequest{}

// ChannelmanagerCreateMarketRequest struct for ChannelmanagerCreateMarketRequest
type ChannelmanagerCreateMarketRequest struct {
	TenantId *string `json:"tenantId,omitempty"`
	Name *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Countries []ChannelmanagerCountryCode `json:"countries,omitempty"`
}

// NewChannelmanagerCreateMarketRequest instantiates a new ChannelmanagerCreateMarketRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelmanagerCreateMarketRequest() *ChannelmanagerCreateMarketRequest {
	this := ChannelmanagerCreateMarketRequest{}
	return &this
}

// NewChannelmanagerCreateMarketRequestWithDefaults instantiates a new ChannelmanagerCreateMarketRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelmanagerCreateMarketRequestWithDefaults() *ChannelmanagerCreateMarketRequest {
	this := ChannelmanagerCreateMarketRequest{}
	return &this
}

// GetTenantId returns the TenantId field value if set, zero value otherwise.
func (o *ChannelmanagerCreateMarketRequest) GetTenantId() string {
	if o == nil || IsNil(o.TenantId) {
		var ret string
		return ret
	}
	return *o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerCreateMarketRequest) GetTenantIdOk() (*string, bool) {
	if o == nil || IsNil(o.TenantId) {
		return nil, false
	}
	return o.TenantId, true
}

// HasTenantId returns a boolean if a field has been set.
func (o *ChannelmanagerCreateMarketRequest) HasTenantId() bool {
	if o != nil && !IsNil(o.TenantId) {
		return true
	}

	return false
}

// SetTenantId gets a reference to the given string and assigns it to the TenantId field.
func (o *ChannelmanagerCreateMarketRequest) SetTenantId(v string) {
	o.TenantId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ChannelmanagerCreateMarketRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerCreateMarketRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ChannelmanagerCreateMarketRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ChannelmanagerCreateMarketRequest) SetName(v string) {
	o.Name = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ChannelmanagerCreateMarketRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerCreateMarketRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ChannelmanagerCreateMarketRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ChannelmanagerCreateMarketRequest) SetDescription(v string) {
	o.Description = &v
}

// GetCountries returns the Countries field value if set, zero value otherwise.
func (o *ChannelmanagerCreateMarketRequest) GetCountries() []ChannelmanagerCountryCode {
	if o == nil || IsNil(o.Countries) {
		var ret []ChannelmanagerCountryCode
		return ret
	}
	return o.Countries
}

// GetCountriesOk returns a tuple with the Countries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelmanagerCreateMarketRequest) GetCountriesOk() ([]ChannelmanagerCountryCode, bool) {
	if o == nil || IsNil(o.Countries) {
		return nil, false
	}
	return o.Countries, true
}

// HasCountries returns a boolean if a field has been set.
func (o *ChannelmanagerCreateMarketRequest) HasCountries() bool {
	if o != nil && !IsNil(o.Countries) {
		return true
	}

	return false
}

// SetCountries gets a reference to the given []ChannelmanagerCountryCode and assigns it to the Countries field.
func (o *ChannelmanagerCreateMarketRequest) SetCountries(v []ChannelmanagerCountryCode) {
	o.Countries = v
}

func (o ChannelmanagerCreateMarketRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelmanagerCreateMarketRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TenantId) {
		toSerialize["tenantId"] = o.TenantId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Countries) {
		toSerialize["countries"] = o.Countries
	}
	return toSerialize, nil
}

type NullableChannelmanagerCreateMarketRequest struct {
	value *ChannelmanagerCreateMarketRequest
	isSet bool
}

func (v NullableChannelmanagerCreateMarketRequest) Get() *ChannelmanagerCreateMarketRequest {
	return v.value
}

func (v *NullableChannelmanagerCreateMarketRequest) Set(val *ChannelmanagerCreateMarketRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelmanagerCreateMarketRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelmanagerCreateMarketRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelmanagerCreateMarketRequest(val *ChannelmanagerCreateMarketRequest) *NullableChannelmanagerCreateMarketRequest {
	return &NullableChannelmanagerCreateMarketRequest{value: val, isSet: true}
}

func (v NullableChannelmanagerCreateMarketRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelmanagerCreateMarketRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


