/*
Channel Manager Service

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
Contact: info@gemini-commerce.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package channelmanager

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ChannelmanagerGetChannelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelmanagerGetChannelRequest{}

// ChannelmanagerGetChannelRequest struct for ChannelmanagerGetChannelRequest
type ChannelmanagerGetChannelRequest struct {
	TenantId string `json:"tenantId"`
	Id string `json:"id"`
}

type _ChannelmanagerGetChannelRequest ChannelmanagerGetChannelRequest

// NewChannelmanagerGetChannelRequest instantiates a new ChannelmanagerGetChannelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelmanagerGetChannelRequest(tenantId string, id string) *ChannelmanagerGetChannelRequest {
	this := ChannelmanagerGetChannelRequest{}
	this.TenantId = tenantId
	this.Id = id
	return &this
}

// NewChannelmanagerGetChannelRequestWithDefaults instantiates a new ChannelmanagerGetChannelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelmanagerGetChannelRequestWithDefaults() *ChannelmanagerGetChannelRequest {
	this := ChannelmanagerGetChannelRequest{}
	return &this
}

// GetTenantId returns the TenantId field value
func (o *ChannelmanagerGetChannelRequest) GetTenantId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TenantId
}

// GetTenantIdOk returns a tuple with the TenantId field value
// and a boolean to check if the value has been set.
func (o *ChannelmanagerGetChannelRequest) GetTenantIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TenantId, true
}

// SetTenantId sets field value
func (o *ChannelmanagerGetChannelRequest) SetTenantId(v string) {
	o.TenantId = v
}

// GetId returns the Id field value
func (o *ChannelmanagerGetChannelRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ChannelmanagerGetChannelRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ChannelmanagerGetChannelRequest) SetId(v string) {
	o.Id = v
}

func (o ChannelmanagerGetChannelRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelmanagerGetChannelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["tenantId"] = o.TenantId
	toSerialize["id"] = o.Id
	return toSerialize, nil
}

func (o *ChannelmanagerGetChannelRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"tenantId",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varChannelmanagerGetChannelRequest := _ChannelmanagerGetChannelRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varChannelmanagerGetChannelRequest)

	if err != nil {
		return err
	}

	*o = ChannelmanagerGetChannelRequest(varChannelmanagerGetChannelRequest)

	return err
}

type NullableChannelmanagerGetChannelRequest struct {
	value *ChannelmanagerGetChannelRequest
	isSet bool
}

func (v NullableChannelmanagerGetChannelRequest) Get() *ChannelmanagerGetChannelRequest {
	return v.value
}

func (v *NullableChannelmanagerGetChannelRequest) Set(val *ChannelmanagerGetChannelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelmanagerGetChannelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelmanagerGetChannelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelmanagerGetChannelRequest(val *ChannelmanagerGetChannelRequest) *NullableChannelmanagerGetChannelRequest {
	return &NullableChannelmanagerGetChannelRequest{value: val, isSet: true}
}

func (v NullableChannelmanagerGetChannelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelmanagerGetChannelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


